In [1]:
import pandas as pd 
import numpy as np 

In [2]:
import os 
os.chdir('..')

In [3]:
from pyod.utils import generate_data

In [4]:
from pyemits.core.ml.anomaly_detection.trainer import AnomalyTrainer, AnomalyDataModel, PyodWrapper

In [5]:
from pyod.models.lof import LOF
from pyod.models.cof import COF
from pyod.models.iforest import IForest


In [6]:
contamination = 0.1  # percentage of outliers
n_train = 1000  # number of training points
n_test = 200  # number of testing points

X_train, y_train, X_test, y_test = generate_data(
    n_train=n_train, n_test=n_test, contamination=contamination)

/Users/kinshingwong/Library/Caches/pypoetry/virtualenvs/pyemits-BM0BzTys-py3.8/lib/python3.8/site-packages/pyod/utils/data.py:186: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.9.0. Please use behaviour="new", which makes the returned datasets in the order of X_train, X_test, y_train, y_test.
  warn('behaviour="old" is deprecated and will be removed '


# Detector Training

followings are acceptable:

> str

> PyodWrapper without model initialization

> PyodWrapper with model initialization are acceptable

In [7]:
detector = AnomalyTrainer(['IForest', PyodWrapper(IForest()),PyodWrapper(IForest),'IForest','IForest' ,'IForest'],None, AnomalyDataModel(X_train))


In [37]:
from pyemits.common.config_model import PyodIforestConfig
detector = AnomalyTrainer([PyodWrapper(IForest(contamination=0.05)),PyodWrapper(IForest)],[None, PyodIforestConfig(contamination=0.05)] , AnomalyDataModel(X_train))


In [38]:
detector.fit()

In [39]:
detector.clf_models

SliceableDeque([('PyodWrapper_None',
                 <pyemits.core.ml.anomaly_detection.trainer.PyodWrapper at 0x7f9ad203c5b0>),
                ('PyodWrapper_None',
                 <pyemits.core.ml.anomaly_detection.trainer.PyodWrapper at 0x7f9ad20396a0>)])

# detector Prediction

In [40]:
from pyemits.core.ml.anomaly_detection.predictor import AnomalyPredictor

### no existing standard scaler

In [41]:

predictor = AnomalyPredictor(detector.clf_models)
predictor.predict(AnomalyDataModel(X_test))

creating new standard scaler


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1])

### passing existing standard scaler

In [25]:
predictor = AnomalyPredictor(detector.clf_models, other_config={'standard_scaler': predictor.misc_container['standard_scaler']})

In [26]:
predictor.predict(AnomalyDataModel(X_test))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [27]:
predictor._cal_anomaly_score(AnomalyDataModel(X_test))

SliceableDeque([array([-0.2579304 , -0.2033623 , -0.60020724, -0.37128163, -0.29644007,
                        0.17134566, -0.27607599,  0.60075959,  0.01152652, -0.62558516,
                        0.01900286, -0.4342206 , -0.65187732, -0.43412887, -0.45930062,
                       -0.71749088,  0.11707693, -0.70304796, -0.55199273, -0.29509767,
                       -0.35169524,  0.06788269, -0.63321342, -0.6136166 ,  0.3874584 ,
                       -0.57716474, -0.61666826, -0.62701222, -0.60576206, -0.70878643,
                        0.01341791, -0.64451515,  0.12169867, -0.6879473 , -0.66956145,
                       -0.75840476, -0.48480403, -0.7566398 ,  0.39273167, -0.16406513,
                       -0.22008334, -0.40871189, -0.47304236,  1.25717918, -0.7301707 ,
                       -0.26234363, -0.25625351, -0.60288501,  0.69831863, -0.73258549,
                       -0.15331944, -0.1844974 , -0.51254431, -0.7059928 , -0.38890421,
                       -0.632472

### combination usage

In [22]:
predictor = AnomalyPredictor(detector.clf_models, 
                            other_config={'standard_scaler': predictor.misc_container['standard_scaler'],
                                         'combination_config': {'n_buckets': 3}
                                         },
                            combination_method='moa')

In [23]:
predictor.predict(AnomalyDataModel(X_test))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

In [24]:
predictor._cal_anomaly_score(AnomalyDataModel(X_test))

SliceableDeque([array([-0.22943703, -0.15566062, -0.59389379, -0.34861683, -0.2609089 ,
                        0.21917932, -0.25417488,  0.68183493,  0.05460252, -0.54259298,
                        0.08942245, -0.40507084, -0.58488718, -0.42647511, -0.41727106,
                       -0.69145264,  0.12843105, -0.67881234, -0.51262903, -0.27661715,
                       -0.31288599,  0.10497459, -0.61799891, -0.55616585,  0.46751829,
                       -0.55097034, -0.60915935, -0.59473687, -0.58433867, -0.69382992,
                        0.09133044, -0.62165315,  0.12416252, -0.63408675, -0.63443704,
                       -0.7517994 , -0.43445055, -0.72326861,  0.45544832, -0.10701349,
                       -0.1970593 , -0.38320331, -0.43166401,  1.34789531, -0.68340098,
                       -0.22836709, -0.22191875, -0.54764801,  0.90385283, -0.71691832,
                       -0.12838106, -0.14321366, -0.46968939, -0.66011958, -0.34171868,
                       -0.580280